"""add user relationship to reservation

Revision ID: 3151c900518d
Revises: 46116121651f
Create Date: 2023-02-27 17:06:59.202890

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '3151c900518d'
down_revision = '46116121651f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_reservation_user_id_user', 'user',
                                    ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.drop_constraint('fk_reservation_user_id_user',
                                 type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
